version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/int128/hello-go-webhook
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/golang/lint/golint
      - run: golint ./...
      - run: go build
